get_all_from table() method is written
solanum-tuberosums/bangazon_terminal_interface pull request #26
Opened 2017-05-08 20:43 UTC by zakspence

## Associated Ticket
[User can choose an active customer from a list of all customers](https://github.com/solanum-tuberosums/bangazon_terminal_interface/issues/5)
[User can choose an active customer from a list of all customers](https://github.com/solanum-tuberosums/bangazon_terminal_interface/issues/5)

## Description 
This method will successfully query the 'customer' table or the 'product' table. The command is written as a string which includes an order by statement. The statement uses a different string for ordering depending on whether 'customer' or 'product' is queried. So when you query the customers, we order by 'last_name', whereas when you query the products we order by 'title'. 

Since the sql statement uses a variable to order the query, and the variable is only set when 'customer' or 'product' is queried, this command should error if any other table is queried, even if the table exists in the database.

## All Tests Pass
- [ ] Yes
- [x] No

2017-05-08 20:51 UTC, JeremyBakker requested changes
When running the test suite, I get the following error: 
```======================================================================
ERROR: test_get_all_from_customer_and_set_active_customer (TestDB.TestDatabaseInteractions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jeremybakker/workspace/bangazon_group_work/bangazon_terminal_interface/test/TestDB.py", line 168, in test_get_all_from_customer_and_set_active_customer
    active_customer_id = customer_list[chosen_customer_from_menu-1][chosen_customer_pk_index]
TypeError: 'sqlite3.Cursor' object is not subscriptable

----------------------------------------------------------------------
```

2017-05-09 14:04 UTC, willsims14 submitted a review, later dismissed
2 does not equal 1

2017-05-09 14:10 UTC, JeremyBakker requested changes
Our notation/math is off somewhere. Still get an error after refactoring:

```======================================================================
FAIL: test_add_product_to_order (TestDB.TestDatabaseInteractions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jeremybakker/workspace/bangazon_group_work/bangazon_terminal_interface/test/TestDB.py", line 94, in test_add_product_to_order
    self.assertEqual(first_product_id, first_chosen_product_id)
AssertionError: 28 != 29

----------------------------------------------------------------------
```
Will gets AssertionError: 1 !=2.
Zak gets AssertionError: 12 !=13

Perhaps obviously, we're off by 1.

2017-05-09 14:23 UTC, JeremyBakker commented
The test is factored incorrectly. Please remove the "-1" from lines 90 and 91.

2017-05-09 14:31 UTC, JeremyBakker commented
Line 78 in TestDB.py is duplicate. It should be deleted. We should refactor accordingly.

2017-05-09 14:44 UTC, JeremyBakker requested changes
Can you strike line 85 in TestDB.py?

2017-05-09 14:45 UTC, BlaiseRoberts approved these changes
🥇

2017-05-09 14:45 UTC, JeremyBakker approved these changes
Great. Thanks!

2017-05-09 14:46 UTC, merged